apiVersion: v1
kind: Pod
metadata: 
  name: api
  labels: 
    app: api
spec:
  containers:
  - name: api
    image: lucmally/quotes-back:v2
    ports:
    - name: api-port
      containerPort: 5000
      protocol: TCP
