apiVersion: apps/v1
kind: Deployment
metadata:
  name: data
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: lucmally/quotes-data:v1
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: mydatabase
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage  
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      initContainers:
      - name: init-db
        image: eon01/quotes-data:v1
        command: ['mysql', '-u$MYSQL_USER', '-p$MYSQL_ROOT_PASSWORD', '-h','0.0.0.0', '<', '/tmp/mydatabase.sql']
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: mydatabase
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: root
---
apiVersion: v1
kind: Service
metadata:
  name: data
  labels:
    app: api
spec:
  ports:
    - port: 3306
  selector:
    app: api
  clusterIP: None